fix(bitwarden): Update login scripts and vars

diff --git a/roles/bitwarden/bin/_bw-bin-login-script b/roles/bitwarden/bin/_bw-bin-login-script
--- a/roles/bitwarden/bin/_bw-bin-login-script
+++ b/roles/bitwarden/bin/_bw-bin-login-script
@@ -1,7 +1,22 @@
 #!/bin/env bash
 
-session_key=$(bw login --raw)
+bw_status=$(bw status | jq -r '.status')
 
-if [[ "$?" == "0" ]]; then
+if [ "${bw_status}" = "unauthenticated" ]; then
+  session_key=$(bw login --raw)
+
+  if [ $? -ne 0 ]; then
+    echo "Failed to unlock the Bitwarden vault. Please check your password and try again."
+    return 1
+  fi
+  
   export BW_SESSION="$session_key"
+
+elif [ "$bw_status" = "locked" ]; then
+  source _bw-bin-unlock-script
+elif [ "${bw_status}" = "unlocked" ]; then
+  echo "You are already logged in :)"
+else
+  echo "Unknown status code \"${bw_status}\""
+  return 1
 fi
diff --git a/roles/bitwarden/bin/_bw-bin-unlock-script b/roles/bitwarden/bin/_bw-bin-unlock-script
--- a/roles/bitwarden/bin/_bw-bin-unlock-script
+++ b/roles/bitwarden/bin/_bw-bin-unlock-script
@@ -1,9 +1,23 @@
 #!/bin/env bash
 
-session_key=$(bw unlock --raw)
+bw_status=$(bw status | jq -r '.status')
 
-if [[ "$?" == "0" ]]; then
+if [ "$bw_status" = "locked" ]; then
+
+  session_key=$(bw unlock --raw)
+  if [ $? -ne 0 ]; then
+    echo "Failed to unlock the Bitwarden vault. Please check your password and try again."
+    return 1
+  fi
+
   export BW_SESSION="$session_key"
+
+elif [ "${bw_status}" = "unauthenticated" ]; then
+  echo "You are not authenticated for Bitwarden, use bw-login instead."
+  return 1
+elif [ "${bw_status}" = "unlocked" ]; then
+  echo "You are already logged in :)"
 else
-  return "$?"
+  echo "Unknown status code \"${bw_status}\""
+  return 1
 fi
